apiVersion: v2
name: cray-import-config
version: 2.0.0
description: Base chart for importing configuration content into Gitea on Shasta systems.
keywords:
  - gitea
  - cfs
home: https://github.com/Cray-HPE/cray-product-install-charts
sources:
  - https://github.com/Cray-HPE/cray-product-install-charts
maintainers:
- email: randy.kleinman@hpe.com
  name: rkleinman
annotations:
  artifacthub.io/images: |
    - name: cray-product-catalog-update
      image: artifactory.algol60.net/csm-docker/stable/cray-product-catalog-update:1.2.50
  artifacthub.io/license: MIT
