# Full image including repo, e.g. dtr.dev.cray.com/cray/config-image:1.2.3
#                                                   ^                 ^
#                                                   |                 |
#                                             ['repository]         [tag]
config_image:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

# Docker image that will update the product catalog with results of the import
# of images and recipes. Specifies the product catalog ConfigMap as well.
catalog:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/cray-product-catalog-update
    tag: 1.3.1
    pullPolicy: IfNotPresent

  config_map: cray-product-catalog
  config_map_namespace: services

import_job:

  # cf-gitea-import image variables, for more information see
  # https://github.com/Cray-HPE/cf-gitea-import
  CF_IMPORT_PRODUCT_NAME: ""
  CF_IMPORT_PRODUCT_VERSION: ""
  CF_IMPORT_GITEA_URL: "http://gitea-vcs"
  CF_IMPORT_GITEA_ORG: "cray"
  CF_IMPORT_GITEA_REPO: ""
  CF_IMPORT_BASE_BRANCH: "semver_previous_if_exists"
  CF_IMPORT_CONTENT: "/content"
  CF_IMPORT_PROTECT_BRANCH: "true"
  CF_IMPORT_PRIVATE_REPO: "true"

  # Specify the user/password of the gitea user from a k8s secret
  CF_IMPORT_GITEA_USER_SECRET: "vcs-user-credentials"
  CF_IMPORT_GITEA_USER_SECRET_KEY: "vcs_username"
  CF_IMPORT_GITEA_PASSWORD_SECRET: "vcs-user-credentials"
  CF_IMPORT_GITEA_PASSWORD_SECRET_KEY: "vcs_password"

  # Additional containers to run along with the content-import container
  initContainers: []
  additionalContainers: []
  additionalVolumes: []
  nodeSelector: {}
